package com.syning.mybatis.mappers;

import com.syning.mybatis.entity.Message;
import com.syning.mybatis.entity.MessageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    int countByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    int deleteByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    int insertSelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    List<Message> selectByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    Message selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    int updateByExampleSelective(@Param("record") Message record, @Param("example") MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    int updateByExample(@Param("record") Message record, @Param("example") MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    int updateByPrimaryKeySelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    int updateByPrimaryKey(Message record);
}