package com.syning.mybatis.mappers;

import com.syning.mybatis.entity.Person;
import com.syning.mybatis.entity.PersonExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    int countByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    int deleteByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    List<Person> selectByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    Person selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    int updateByExampleSelective(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    int updateByExample(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    int updateByPrimaryKeySelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    int updateByPrimaryKey(Person record);
}