package com.syning.mybatis.entity;

public class Person {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.pid
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.p_name
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    private String pName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.p_age
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    private Integer pAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.p_sex
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    private String pSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.mid
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.pwd
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    private String pwd;


    public Person() {}

    public Person(Integer pid, String pName, Integer pAge, String pSex, Integer mid, String pwd) {
        this.pid = pid;
        this.pName = pName;
        this.pAge = pAge;
        this.pSex = pSex;
        this.mid = mid;
        this.pwd = pwd;
    }

    @Override
    public String toString() {
        return "Person{" +
                "pid=" + pid +
                ", pName='" + pName + '\'' +
                ", pAge=" + pAge +
                ", pSex='" + pSex + '\'' +
                ", mid=" + mid +
                ", pwd='" + pwd + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.pid
     *
     * @return the value of t_person.pid
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.pid
     *
     * @param pid the value for t_person.pid
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.p_name
     *
     * @return the value of t_person.p_name
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.p_name
     *
     * @param pName the value for t_person.p_name
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.p_age
     *
     * @return the value of t_person.p_age
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    public Integer getpAge() {
        return pAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.p_age
     *
     * @param pAge the value for t_person.p_age
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    public void setpAge(Integer pAge) {
        this.pAge = pAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.p_sex
     *
     * @return the value of t_person.p_sex
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    public String getpSex() {
        return pSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.p_sex
     *
     * @param pSex the value for t_person.p_sex
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    public void setpSex(String pSex) {
        this.pSex = pSex == null ? null : pSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.mid
     *
     * @return the value of t_person.mid
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.mid
     *
     * @param mid the value for t_person.mid
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.pwd
     *
     * @return the value of t_person.pwd
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.pwd
     *
     * @param pwd the value for t_person.pwd
     *
     * @mbggenerated Tue Apr 26 15:55:19 CST 2022
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }
}